### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by chorny** [imacat/DbFramework#1]
Asks questions in Makefile.PL/Build.PL, I think due to DbFramework::Util::get_auth(). This prevents cpantesters smoker from functioning correctly: they cannot test this module and smoker hangs. Test::Database can be used for test database info.
Environment variables PERL_MM_USE_DEFAULT or AUTOMATED_TESTING can be used to skip questions.

**Comment by imacat** [comment]
Hi.  Thank you for reporting.  Sorry for the delay.  I was traveling home yesterday for my Chinese New Year.
I suppose in my configuration in Makefile.PL and Build.PL, empty answers will be fill into the questions when STDIN is not available.  Could you please tell me your environment and the procedure so that I can try to reproduce it?  Thank you.

**Comment by imacat** [comment]
This should be fixed in 1.14.  Please open a new issue if not.

**Comment by imacat** [comment]
This should be fixed in version 1.14.  Please file a new issue if not.  Thank you.
